import React, { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, CreditCard, Headphones, Lock, LogIn, LogOut, Music, ShieldCheck, Sparkles, Ticket, UserPlus, Wallet } from 'lucide-react';
import { requestBaseUsdcPayment, switchToBase } from './blockchain';

type Category = 'Celebrity Activity' | 'Live Bookings' | 'Music & Lyrics' | 'Backstage Vault' | 'Fan Community';
type Activity = { title: string; detail: string; time: string; status: string };
type Session = { id: string; name: string; email: string; paid: boolean; categories: Category[]; walletAddress?: string; transactionHash?: string };
type EthereumWindow = Window & { ethereum?: { request: (args: { method: string; params?: unknown[] }) => Promise<unknown> } };
const SESSION_KEY = 'nikos-vertis-auth-session'; const USERS_KEY = 'nikos-vertis-users';
const masks: Record<Category, number> = { 'Celebrity Activity': 1, 'Live Bookings': 2, 'Music & Lyrics': 4, 'Backstage Vault': 8, 'Fan Community': 16 };
const categoryInfo: Record<Category, { description: string; icon: React.ElementType; activities: Activity[] }> = {
  'Celebrity Activity': { description: 'Appearances, announcements, interviews, and verified artist updates.', icon: Sparkles, activities: [{ title: 'YTON Saturday residency update', detail: 'The latest official stage and appearance notes are ready for members.', time: 'Today', status: 'New' }, { title: 'Artist announcement', detail: 'Verified news and public appearances from the official platform.', time: 'Yesterday', status: 'Verified' }, { title: 'Fan spotlight', detail: 'A community highlight selected by the editorial team.', time: '3 days ago', status: 'Featured' }] },
  'Live Bookings': { description: 'Upcoming events, table information, tickets, and booking activity.', icon: Ticket, activities: [{ title: 'YTON Athens — Saturday night', detail: 'View event details, availability, and booking instructions.', time: 'This week', status: 'Upcoming' }, { title: 'Booking request status', detail: 'Your booking activity and reservation updates appear here.', time: '2 days ago', status: 'Active' }, { title: 'Venue guide', detail: 'Arrival times, venue information, and member access guidance.', time: '1 week ago', status: 'Guide' }] },
  'Music & Lyrics': { description: 'Songs, lyrics, translations, listening notes, and music stories.', icon: Music, activities: [{ title: 'Song of the week', detail: 'Listen, read the story behind the track, and explore the lyrics.', time: 'Today', status: 'Featured' }, { title: 'Lyrics translation room', detail: 'Compare Greek lyrics with the official English translation.', time: '4 days ago', status: 'Updated' }, { title: 'Bouzouki notes', detail: 'Music discussion and performance notes from the community.', time: '1 week ago', status: 'Discussion' }] },
  'Backstage Vault': { description: 'Exclusive concerts, acoustic sessions, and private member content.', icon: Headphones, activities: [{ title: 'Acoustic session', detail: 'An intimate performance is available in the members vault.', time: 'Today', status: 'Locked preview' }, { title: 'Behind the stage', detail: 'Explore production stories and rehearsal moments.', time: '5 days ago', status: 'Exclusive' }, { title: 'Artist Q&A replay', detail: 'Watch the latest verified member Q&A replay.', time: '2 weeks ago', status: 'Replay' }] },
  'Fan Community': { description: 'Fan stories, discussions, announcements, and member conversations.', icon: ShieldCheck, activities: [{ title: 'Community discussion', detail: 'Share your favorite live performance and join the conversation.', time: 'Today', status: 'Open' }, { title: 'Official announcement board', detail: 'Verified notices from the platform team appear here.', time: 'Yesterday', status: 'Official' }, { title: 'Fan stories', detail: 'Read stories from members around the world.', time: '3 days ago', status: 'Community' }] },
};
const allCategories = Object.keys(categoryInfo) as Category[];
function readSession(): Session | null { try { return JSON.parse(localStorage.getItem(SESSION_KEY) || 'null'); } catch { return null; } }
function readUsers(): any[] { try { return JSON.parse(localStorage.getItem(USERS_KEY) || '[]'); } catch { return []; } }
function maskFor(items: Category[]) { return items.reduce((sum, item) => sum + masks[item], 0); }

export default function PortalApp() {
  const [session, setSession] = useState<Session | null>(() => readSession()); const [selected, setSelected] = useState<Category[]>(() => readSession()?.categories || []); const [active, setActive] = useState<Category | null>(null); const [authMode, setAuthMode] = useState<'login' | 'signup'>('signup'); const [showAuth, setShowAuth] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (session) localStorage.setItem(SESSION_KEY, JSON.stringify(session)); else localStorage.removeItem(SESSION_KEY); }, [session]);
  const toggle = (category: Category) => setSelected((current) => current.includes(category) ? current.filter((item) => item !== category) : [...current, category]);
  const submitAuth = (event: React.FormEvent) => { event.preventDefault(); const email = form.email.trim().toLowerCase(); const password = form.password.trim(); if (!email || !password || (authMode === 'signup' && !form.name.trim())) return setNotice('Complete all fields first.'); const list = readUsers(); if (authMode === 'signup') { if (list.some((item) => item.email === email)) return setNotice('An account already exists.'); const user = { id: `user-${Date.now()}`, name: form.name.trim(), email, password, paid: false, categories: [] }; localStorage.setItem(USERS_KEY, JSON.stringify([...list, user])); setSession(user); setShowAuth(false); return; } const user = list.find((item) => item.email === email && item.password === password); if (!user) return setNotice('Invalid email or password.'); setSession(user); setSelected(user.categories || []); setShowAuth(false); };
  const connectAndPay = async () => { if (!session || selected.length === 0) return setNotice('Select at least one category.'); const provider = (window as EthereumWindow).ethereum; if (!provider) return setNotice('Install MetaMask or another Base-compatible wallet.'); setBusy(true); setNotice('Switching to Base Mainnet…'); try { await switchToBase(provider); setNotice('Approve the 43 USDC payment in your wallet…'); const payment = await requestBaseUsdcPayment(provider); const next = { ...session, paid: true, categories: selected, walletAddress: payment.sender, transactionHash: payment.hash }; localStorage.setItem(USERS_KEY, JSON.stringify(readUsers().map((user) => user.id === session.id ? next : user))); setSession(next); setNotice(`Payment submitted: ${payment.hash.slice(0, 10)}…`); } catch (error) { setNotice(error instanceof Error ? error.message : 'Payment was cancelled.'); } finally { setBusy(false); } };
  if (!session) return <Landing showAuth={showAuth} setShowAuth={setShowAuth} mode={authMode} setMode={setAuthMode} form={form} setForm={setForm} submit={submitAuth} notice={notice} />;
  return <Dashboard session={session} selected={selected} setSelected={setSelected} active={active} setActive={setActive} toggle={toggle} pay={connectAndPay} busy={busy} notice={notice} logout={() => setSession(null)} />;
}

function Header({ logout, onLogin, onSignup }: { logout?: () => void; onLogin?: () => void; onSignup?: () => void }) { return <header className="border-b border-[#1d2332] bg-[#101623]/95"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#d4af37]/15 p-3 text-[#e5c158]"><Sparkles className="h-5 w-5" /></div><div><div className="text-xs uppercase tracking-[.3em] text-[#d4af37]">Nikos Vertis</div><div className="text-sm font-semibold">Official Fan Platform</div></div></div>{logout ? <button onClick={logout} className="inline-flex items-center gap-2 rounded-xl border border-[#2a3142] px-4 py-2 text-sm"><LogOut className="h-4 w-4" /> Log out</button> : <div className="flex gap-3"><button onClick={onLogin} className="rounded-xl border border-[#2a3142] px-4 py-2 text-sm">Log in</button><button onClick={onSignup} className="rounded-xl bg-[#d4af37] px-4 py-2 text-sm font-bold text-black">Sign up</button></div>}</div></header>; }

function Landing({ showAuth, setShowAuth, mode, setMode, form, setForm, submit, notice }: any) { if (showAuth) return <div className="min-h-screen bg-[#0b0c10] px-6 py-16 text-white"><div className="mx-auto max-w-md rounded-3xl border border-[#2a3142] bg-[#111827] p-8"><button onClick={() => setShowAuth(false)} className="mb-6 text-sm text-slate-400">← Back</button><h1 className="text-3xl font-black">{mode === 'signup' ? 'Create your account' : 'Log in'}</h1><div className="my-6 grid grid-cols-2 gap-2 rounded-xl bg-[#0f172a] p-1"><button onClick={() => setMode('signup')} className={`rounded-lg py-2 text-sm ${mode === 'signup' ? 'bg-[#d4af37] text-black' : ''}`}>Sign up</button><button onClick={() => setMode('login')} className={`rounded-lg py-2 text-sm ${mode === 'login' ? 'bg-[#d4af37] text-black' : ''}`}>Log in</button></div><form onSubmit={submit} className="space-y-4">{mode === 'signup' && <input placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full rounded-xl bg-[#0f172a] p-3" />}<input placeholder="Email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="w-full rounded-xl bg-[#0f172a] p-3" /><input placeholder="Password" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="w-full rounded-xl bg-[#0f172a] p-3" />{notice && <p className="text-sm text-[#f5d98a]">{notice}</p>}<button className="w-full rounded-xl bg-[#d4af37] py-3 font-bold text-black">Continue</button></form></div></div>; return <div className="min-h-screen bg-[#0b0c10] text-white"><Header onLogin={() => { setMode('login'); setShowAuth(true); }} onSignup={() => { setMode('signup'); setShowAuth(true); }} /><main className="mx-auto max-w-7xl px-6 py-24"><div className="max-w-2xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#d4af37]/40 px-3 py-1 text-xs uppercase tracking-widest text-[#f0d88e]"><ShieldCheck className="h-4 w-4" /> Verified fan access</div><h1 className="text-5xl font-black md:text-6xl">Your official <span className="text-[#d4af37]">fan dashboard.</span></h1><p className="mt-6 text-lg leading-8 text-slate-300">Choose the categories you love and explore every activity in one personalized portal.</p><button onClick={() => { setMode('signup'); setShowAuth(true); }} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#d4af37] px-6 py-3 font-bold text-black">Get started <ArrowRight className="h-4 w-4" /></button></div></main></div>; }

function Dashboard({ session, selected, active, setActive, toggle, pay, busy, notice, logout }: any) { const visible = session.paid ? selected : allCategories; return <div className="min-h-screen bg-[#0b0c10] text-white"><Header logout={logout} /><main className="mx-auto max-w-7xl px-6 py-10"><div className="rounded-3xl border border-[#2a3142] bg-gradient-to-r from-[#141d30] to-[#0d1118] p-8"><div className="text-xs uppercase tracking-[.25em] text-[#d4af37]">{session.paid ? 'Access unlocked' : 'Member dashboard'}</div><h1 className="mt-3 text-4xl font-black">Welcome, {session.name}</h1><p className="mt-3 text-slate-300">Click any layout to preview its activities. Use “See activities” for the dedicated activity view.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map((category: Category) => { const info = categoryInfo[category]; const Icon = info.icon; const locked = !session.paid && !selected.includes(category); return <button key={category} onClick={() => setActive(category)} className={`rounded-3xl border p-6 text-left transition hover:-translate-y-1 ${active === category ? 'border-[#d4af37] bg-[#d4af37]/10' : 'border-[#1d2332] bg-[#101725]'}`}><div className="flex justify-between"><span className="rounded-2xl bg-[#d4af37]/10 p-3 text-[#e5c158]"><Icon className="h-5 w-5" /></span>{locked ? <Lock className="h-5 w-5 text-slate-500" /> : <CheckCircle2 className="h-5 w-5 text-emerald-400" />}</div><h2 className="mt-5 text-xl font-bold">{category}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{info.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#f0d88e]">See activities <ArrowRight className="h-4 w-4" /></span></button>; })}</div>{!session.paid && <div className="mt-8 rounded-3xl border border-[#d4af37]/35 bg-[#111827] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[#f0d88e]"><CreditCard className="h-4 w-4" /> Unlock selected layouts</div><p className="mt-2 text-sm text-slate-300">Select categories, then pay 43 USDC on Base to unlock their activities.</p></div><button onClick={pay} disabled={busy || selected.length === 0} className="rounded-xl bg-[#d4af37] px-5 py-3 font-bold text-black disabled:opacity-50">{busy ? 'Waiting for wallet…' : `Pay 43 USDC • mask ${maskFor(selected)}`}</button></div>{notice && <p className="mt-4 text-sm text-[#f5d98a]">{notice}</p>}</div>}{active && <ActivityLayout category={active} session={session} close={() => setActive(null)} />}</main></div>; }

function ActivityLayout({ category, session, close }: { category: Category; session: Session; close: () => void }) { const info = categoryInfo[category]; const Icon = info.icon; const unlocked = session.paid && session.categories.includes(category); return <section className="mt-10 rounded-3xl border border-[#2a3142] bg-[#101725] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><span className="rounded-2xl bg-[#d4af37]/10 p-3 text-[#e5c158]"><Icon className="h-6 w-6" /></span><div><div className="text-xs uppercase tracking-[.25em] text-[#d4af37]">Dedicated activity layout</div><h2 className="mt-2 text-3xl font-black">{category}</h2><p className="mt-2 max-w-2xl text-sm text-slate-300">{info.description}</p></div></div><button onClick={close} className="inline-flex items-center gap-2 rounded-xl border border-[#2a3142] px-4 py-2 text-sm"><ArrowLeft className="h-4 w-4" /> Back</button></div>{unlocked ? <div className="mt-8 grid gap-4 md:grid-cols-3">{info.activities.map((activity) => <article key={activity.title} className="rounded-2xl border border-[#273047] bg-[#0d1422] p-5"><div className="flex justify-between gap-3 text-xs text-[#d4af37]"><span>{activity.status}</span><span className="text-slate-500">{activity.time}</span></div><h3 className="mt-4 font-bold">{activity.title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{activity.detail}</p><button className="mt-5 text-sm font-bold text-[#f0d88e]">Open activity →</button></article>)}</div> : <div className="mt-8 rounded-2xl border border-[#d4af37]/30 bg-[#d4af37]/10 p-5"><div className="flex items-center gap-2 font-bold text-[#f0d88e]"><Lock className="h-4 w-4" /> This layout is locked</div><p className="mt-2 text-sm text-slate-300">Select this category and complete the 43 USDC Base payment to view its activities.</p></div>}</section>; }
